name: Build
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    builds:
        name: Builds
        runs-on: ubuntu-latest
        strategy:
          matrix:
            platform: [ linux, windows ]
        steps:
            - name: Build for ${{ matrix.platform }}
              id: build
              uses: josephbmanley/build-godot-action@v1.5.0
              with:
                  name: WitchPanic
                  preset: ${{ matrix.platform }}
            - name: Upload ${{ matrix.platform }} artifact
              uses: actions/upload-artifact@v2
              with:
                name: ${{ matrix.platform }} build
                path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
